ZSL_MODEL_NAME: "CADA_VAE"
ZSL:
  BATCH_SIZE: 50
  EPOCH: 100
  SOLVER:
    BASE_LR: 0.00015
    AMSGRAD: True
CLS:
  EPOCH: 40
  BATCH_SIZE: 50
  SOLVER:
    AMSGRAD: True
DATA:
  FEAT_EMB:
    PATH: "datasets/CUB/resnet101/"
